services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  api:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./config.yaml:/app/config.yaml:ro
    command: >-
      sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  celery_worker:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./config.yaml:/app/config.yaml:ro

  celery_beat:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./config.yaml:/app/config.yaml:ro

volumes:
  postgres_data:
  redis_data:
