"""create initial full schema

Revision ID: 1a19b9367fce
Revises:
Create Date: 2025-11-13 16:51:47.098976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector
from utils.config import settings

# Validate embedding dimension before using it in Vector column
dim = settings.EMBEDDING.get("dim")
if not dim or not isinstance(dim, int) or dim <= 0:
    raise ValueError(
        f"Invalid embedding dimension: {dim}. "
        f"Must be a positive integer configured in config.yaml (embedding.embedding_dim)"
    )

# revision identifiers, used by Alembic.
revision: str = '1a19b9367fce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata_content', sa.JSON(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_id'), 'metadata', ['id'], unique=False)
    op.create_index(op.f('ix_metadata_key'), 'metadata', ['key'], unique=False)

    op.create_table('data_embeddings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('metadata_', postgresql.JSONB(), nullable=True),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('embedding', Vector(dim), nullable=True),
    sa.Column('text_search_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('key_text', sa.Text(), sa.Computed("metadata_ ->> 'key'", persisted=True)),
    sa.Column('checksum_text', sa.Text(), sa.Computed("metadata_ ->> 'checksum'", persisted=True)),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # --- Indexes for fast deletion and lookup ---
    op.create_index('idx_data_embeddings_key_text', 'data_embeddings', ['key_text'], schema='public')
    op.create_index('idx_data_embeddings_checksum_text', 'data_embeddings', ['checksum_text'], schema='public')
    op.create_index('idx_data_embeddings_metadata_gin', 'data_embeddings', ['metadata_'], postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_embeddings', schema='public')
    op.drop_index(op.f('ix_metadata_key'), table_name='metadata')
    op.drop_index(op.f('ix_metadata_id'), table_name='metadata')
    op.drop_table('metadata')
    # ### end Alembic commands ###
